excel:
  file: "cases.xlsx"

logger:
  name: primihub-test
  file: 'testlog.txt'
  logger_level: 'DEBUG'
  stream_level: "DEBUG"
  file_level: "INFO"

db:
  host: "192.168.99.13"
  port: 30306
  user: "primihub"
  password: "primihub@123"
  charset: "utf8"

user01:
  userAccount: "test"
  userPassword: "123456"

user02:
  userAccount: "test"
  userPassword: "123456"

test:
  token: "excalibur_forever_ABCDEFGHIJKLMN"
  userid: "1"
  fileId01: "1351"
  fileId02: "1159"

host1: http://test1.primihub.com/prod-api
host2: http://test2.primihub.com/prod-api
host3: http://test3.primihub.com/prod-api


test_name:
  resourceName01: "test1-xgbhost资源"
  resourceName02: "test2-xgbguest资源"
  psiresource01: "test1-psi资源"
  psiresource02: "test2-psi资源"
  lrresource01: "test1-lr资源"
  lrresource02: "test2-lr资源"
  projectName01: "测试新建项目"



