excel:
  file: "cases.xlsx"

logger:
  name: primihub-test
  file: 'testlog.txt'
  logger_level: 'DEBUG'
  stream_level: "DEBUG"
  file_level: "INFO"

db:
  host: "118.190.39.100"
  port: 27936
  user: "primihub"
  password: "primihub@123"
  charset: "utf8"

user01:
  userAccount: "13699223155"
  userPassword: "lyn@123456"

user02:
  userAccount: "test"
  userPassword: "123456"

test:
  token: "excalibur_forever_ABCDEFGHIJKLMN"
  userid: "1"
  fileId01: "1"
  fileId02: "1"

host1: http://172.21.3.16:30811/prod-api
host2: http://172.21.3.59:30811/prod-api
host3: http://172.21.3.108:30811/prod-api


test_name:
  resourceName01: "test1-的新资源"
  resourceName02: "test2-的新资源"
  projectName01: "测试新建项目"



