excel:
  file: "cases.xlsx"

logger:
  name: primihub-test
  file: 'testlog.txt'
  logger_level: 'DEBUG'
  stream_level: "DEBUG"
  file_level: "INFO"

db:
  host: "192.168.99.13"
  port: 30306
  user: "primihub"
  password: "primihub@123"
  charset: "utf8"


host1: http://test1.primihub.com/prod-api
host2: http://test2.primihub.com/prod-api
host3: http://test3.primihub.com/prod-api

user:
  userAccount: "admin"
  userPassword: "123456"

test_data:
  psi_data_01: "psi_a.csv"
  psi_data_02: "psi_b.csv"
  pir_data: "pir.csv"
  h_lr_host: "训练_横向lr_host.csv"
  h_lr_guest: "训练_横向lr_guest.csv"
  yc_lr_host: "推理_横向lr.csv"

  v_host: "训练_纵向xgb_lr_host.csv"
  v_guest: "训练_纵向xgb_lr_guest.csv"
  yc_v_host: "推理_纵向xgb_lr_host.csv"
  yc_v_guest: "推理_纵向xgb_lr_guest.csv"

  mpc_lr_01: "mpc-lr_1.csv"
  mpc_lr_02: "mpc-lr_2.csv"
  mpc_lr_03: "mpc-lr_3.csv"



